#Project Information 
site_name: HNUSEC Wiki
site_description: HNUSEC Wiki
site_author: HNUSEC
site_url: http://wiki.hnusec.group

# Repository
repo_name: DrsEeker/HNUSEC_Wiki
repo_url: 'https://github.com/DrsEeker/HNUSEC_Wiki'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 HNUSEC'

# Content
nav:
    - Introduction:
        - Getting Started: index.md
        - CTF Contest Content: Introduction/contest.md
        - About us: Introduction/about_us.md
    - Course:
        - Introduction: Course/introduction.md
        - Computer Network:
            - Protocol: 
                - DNS: Course/Computer Network/Protocol/dns.md
                - DHCP: Course/Computer Network/Protocol/dhcp.md
                - ICMP: Course/Computer Network/Protocol/icmp.md
            - Resource: Course/Computer Network/resource.md
            - Tools: Course/Computer Network/tools.md
        - Database:
            - Mysql:
                - Course/Database/Mysql/compare.md
    - CTF-Misc:
        - Introduction: CTF-Misc/introduction.md
    - CTF-Web:
        - Introduction: CTF-Web/introduction.md
        - SQL Injection:
            - No Column Injection & Bypass Information_schema: CTF-Web/SQL Injection/NoColumnInjection&BypassInformation_schema.md
    - CTF-Pwn:
        - Introduction: CTF-Pwn/introduction.md
    - CTF-Reverse:
        - Introduction: CTF-Reverse/introduction.md
    - CTF-Crypto:
        - Introduction: CTF-Crypto/introduction.md
    - WriteUps:
        - HNUSEC OJ:
            - 302: Writeups/302/web_302.md
            - cookies: Writeups/cookies/web_cookies.md
            - hidden message: Writeups/hidden message/web_hidden_message.md       
            - PNG: Writeups/PNG/misc_png.md     
    - Papers:
        - Introduction: Papers/introduction.md
    - CVE:
        - Introduction: CVE/introduction.md
    - Links:
        - Introduction: Links/introduction.md
        - Tools: Links/tools.md
        - CTF: Links/CTF/study.md
        - Operating System: 
            - MACOS: Links/Operating System/content.md
    - Reference books & notes:
        - Reference books: Reference books & notes/Links of Reference books.md
        - Notes: 
    -常见问题解答:
        - Introduction: F&Q/introduction.md

theme:
  name: material
  language: 'zh'
  palette:
    primary: 'Teal'
    accent: 'Pink'
  logo:
    icon: 'school'
  feature:
    tabs: true 
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

extra_javascript:
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
